targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
        generate_for:
          include:
            - lib/**.codegen.dart
      freezed:
        generate_for:
          include:
            - lib/**.codegen.dart
      riverpod_generator:
        generate_for:
          include:
            - lib/**.codegen.dart