name: stadium_tickets_app
description: Stadium tickets app made with Flutter SDK

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animated_custom_dropdown: ^1.5.0
  animations: ^2.0.7
  another_flushbar: ^1.12.29
  audioplayers: ^4.0.1
  cached_network_image: ^3.2.3
  clock: ^1.1.1
  collection: ^1.17.0
  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_secure_storage: ^8.0.0
  flutter_spinkit: ^5.2.0
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.4
  hooks_riverpod: ^2.3.6
  intl: ^0.18.1
  json_annotation: ^4.8.0
  lottie: ^2.3.2
  path: ^1.8.2
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  riverpod_annotation: ^2.1.1
  sentry_flutter: ^7.5.1
  shared_preferences: ^2.1.0
  time: ^2.1.3
  video_player: ^2.6.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.2.1
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/sounds/
