name: stadium_tickets_app
description: Stadium tickets app made with Flutter SDK

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animated_custom_dropdown: ^1.2.2
  animations: ^2.0.7
  another_flushbar: ^1.12.29
  audioplayers: ^1.1.1
  cached_network_image: ^3.2.2
  clock: ^1.1.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_hive_store: ^3.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_secure_storage: ^6.1.0
  flutter_spinkit: ^5.1.0
  freezed_annotation: ^2.2.0
  google_fonts: ^3.0.1
  hooks_riverpod: ^2.1.1
  intl: ^0.17.0
  json_annotation: ^4.7.0
  lottie: ^1.4.3
  path: ^1.8.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  riverpod_annotation: ^1.0.6
  sentry_flutter: ^6.14.0
  shared_preferences: ^2.0.15
  time: ^2.1.3
  video_player: ^2.4.10

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  riverpod_generator: ^1.0.6
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/sounds/
